# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KnowMeAiConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='KnowMeAiConfig.proto',
  package='knowmeai',
  serialized_pb=_b('\n\x14KnowMeAiConfig.proto\x12\x08knowmeai\"\xd9\x05\n\x0csystemConfig\x12.\n\x05sound\x18\x01 \x02(\x0b\x32\x1f.knowmeai.systemConfig.soundCnf\x12\x34\n\x08skeleton\x18\x02 \x02(\x0b\x32\".knowmeai.systemConfig.skeletonCnf\x12,\n\x04\x66\x61\x63\x65\x18\x03 \x02(\x0b\x32\x1e.knowmeai.systemConfig.faceCnf\x12>\n\rcommunication\x18\x04 \x02(\x0b\x32\'.knowmeai.systemConfig.communicationCnf\x1a/\n\x08soundCnf\x12\x12\n\nsampleRate\x18\x01 \x02(\x05\x12\x0f\n\x07samples\x18\x02 \x02(\x05\x1a\x31\n\x0bskeletonCnf\x12\x12\n\nnoOfPoints\x18\x01 \x02(\x05\x12\x0e\n\x06\x66rames\x18\x02 \x02(\x05\x1ai\n\x07\x66\x61\x63\x65\x43nf\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12/\n\x05\x63olor\x18\x03 \x02(\x0e\x32 .knowmeai.systemConfig.colorType\x12\x0e\n\x06\x66rames\x18\x04 \x02(\x05\x1a\x85\x02\n\x10\x63ommunicationCnf\x12\x10\n\x08sensorIp\x18\x01 \x02(\t\x12\x0f\n\x07soundIp\x18\x02 \x02(\t\x12\x0e\n\x06\x66\x61\x63\x65Ip\x18\x03 \x02(\t\x12\x11\n\tgestureIp\x18\x04 \x02(\t\x12\x0e\n\x06syncIp\x18\x05 \x02(\t\x12\x12\n\ncompoundIp\x18\x06 \x02(\t\x12\x12\n\nsensorPort\x18\x07 \x02(\x05\x12\x11\n\tsoundPort\x18\x08 \x02(\x05\x12\x10\n\x08\x66\x61\x63\x65Port\x18\t \x02(\x05\x12\x13\n\x0bgesturePort\x18\n \x02(\x05\x12\x11\n\tstorePort\x18\x0b \x02(\x05\x12\x10\n\x08syncPort\x18\x0c \x02(\x05\x12\x14\n\x0c\x63ompoundPort\x18\r \x02(\x05\"\x1e\n\tcolorType\x12\x07\n\x03RGB\x10\x00\x12\x08\n\x04GREY\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SYSTEMCONFIG_COLORTYPE = _descriptor.EnumDescriptor(
  name='colorType',
  full_name='knowmeai.systemConfig.colorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RGB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=734,
  serialized_end=764,
)
_sym_db.RegisterEnumDescriptor(_SYSTEMCONFIG_COLORTYPE)


_SYSTEMCONFIG_SOUNDCNF = _descriptor.Descriptor(
  name='soundCnf',
  full_name='knowmeai.systemConfig.soundCnf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sampleRate', full_name='knowmeai.systemConfig.soundCnf.sampleRate', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samples', full_name='knowmeai.systemConfig.soundCnf.samples', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=310,
)

_SYSTEMCONFIG_SKELETONCNF = _descriptor.Descriptor(
  name='skeletonCnf',
  full_name='knowmeai.systemConfig.skeletonCnf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='noOfPoints', full_name='knowmeai.systemConfig.skeletonCnf.noOfPoints', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frames', full_name='knowmeai.systemConfig.skeletonCnf.frames', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=361,
)

_SYSTEMCONFIG_FACECNF = _descriptor.Descriptor(
  name='faceCnf',
  full_name='knowmeai.systemConfig.faceCnf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='knowmeai.systemConfig.faceCnf.width', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='knowmeai.systemConfig.faceCnf.height', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='knowmeai.systemConfig.faceCnf.color', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frames', full_name='knowmeai.systemConfig.faceCnf.frames', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=468,
)

_SYSTEMCONFIG_COMMUNICATIONCNF = _descriptor.Descriptor(
  name='communicationCnf',
  full_name='knowmeai.systemConfig.communicationCnf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorIp', full_name='knowmeai.systemConfig.communicationCnf.sensorIp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='soundIp', full_name='knowmeai.systemConfig.communicationCnf.soundIp', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='faceIp', full_name='knowmeai.systemConfig.communicationCnf.faceIp', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gestureIp', full_name='knowmeai.systemConfig.communicationCnf.gestureIp', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='syncIp', full_name='knowmeai.systemConfig.communicationCnf.syncIp', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compoundIp', full_name='knowmeai.systemConfig.communicationCnf.compoundIp', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensorPort', full_name='knowmeai.systemConfig.communicationCnf.sensorPort', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='soundPort', full_name='knowmeai.systemConfig.communicationCnf.soundPort', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='facePort', full_name='knowmeai.systemConfig.communicationCnf.facePort', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gesturePort', full_name='knowmeai.systemConfig.communicationCnf.gesturePort', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='storePort', full_name='knowmeai.systemConfig.communicationCnf.storePort', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='syncPort', full_name='knowmeai.systemConfig.communicationCnf.syncPort', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compoundPort', full_name='knowmeai.systemConfig.communicationCnf.compoundPort', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=732,
)

_SYSTEMCONFIG = _descriptor.Descriptor(
  name='systemConfig',
  full_name='knowmeai.systemConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sound', full_name='knowmeai.systemConfig.sound', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skeleton', full_name='knowmeai.systemConfig.skeleton', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='face', full_name='knowmeai.systemConfig.face', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='communication', full_name='knowmeai.systemConfig.communication', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SYSTEMCONFIG_SOUNDCNF, _SYSTEMCONFIG_SKELETONCNF, _SYSTEMCONFIG_FACECNF, _SYSTEMCONFIG_COMMUNICATIONCNF, ],
  enum_types=[
    _SYSTEMCONFIG_COLORTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=764,
)

_SYSTEMCONFIG_SOUNDCNF.containing_type = _SYSTEMCONFIG
_SYSTEMCONFIG_SKELETONCNF.containing_type = _SYSTEMCONFIG
_SYSTEMCONFIG_FACECNF.fields_by_name['color'].enum_type = _SYSTEMCONFIG_COLORTYPE
_SYSTEMCONFIG_FACECNF.containing_type = _SYSTEMCONFIG
_SYSTEMCONFIG_COMMUNICATIONCNF.containing_type = _SYSTEMCONFIG
_SYSTEMCONFIG.fields_by_name['sound'].message_type = _SYSTEMCONFIG_SOUNDCNF
_SYSTEMCONFIG.fields_by_name['skeleton'].message_type = _SYSTEMCONFIG_SKELETONCNF
_SYSTEMCONFIG.fields_by_name['face'].message_type = _SYSTEMCONFIG_FACECNF
_SYSTEMCONFIG.fields_by_name['communication'].message_type = _SYSTEMCONFIG_COMMUNICATIONCNF
_SYSTEMCONFIG_COLORTYPE.containing_type = _SYSTEMCONFIG
DESCRIPTOR.message_types_by_name['systemConfig'] = _SYSTEMCONFIG

systemConfig = _reflection.GeneratedProtocolMessageType('systemConfig', (_message.Message,), dict(

  soundCnf = _reflection.GeneratedProtocolMessageType('soundCnf', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMCONFIG_SOUNDCNF,
    __module__ = 'KnowMeAiConfig_pb2'
    # @@protoc_insertion_point(class_scope:knowmeai.systemConfig.soundCnf)
    ))
  ,

  skeletonCnf = _reflection.GeneratedProtocolMessageType('skeletonCnf', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMCONFIG_SKELETONCNF,
    __module__ = 'KnowMeAiConfig_pb2'
    # @@protoc_insertion_point(class_scope:knowmeai.systemConfig.skeletonCnf)
    ))
  ,

  faceCnf = _reflection.GeneratedProtocolMessageType('faceCnf', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMCONFIG_FACECNF,
    __module__ = 'KnowMeAiConfig_pb2'
    # @@protoc_insertion_point(class_scope:knowmeai.systemConfig.faceCnf)
    ))
  ,

  communicationCnf = _reflection.GeneratedProtocolMessageType('communicationCnf', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMCONFIG_COMMUNICATIONCNF,
    __module__ = 'KnowMeAiConfig_pb2'
    # @@protoc_insertion_point(class_scope:knowmeai.systemConfig.communicationCnf)
    ))
  ,
  DESCRIPTOR = _SYSTEMCONFIG,
  __module__ = 'KnowMeAiConfig_pb2'
  # @@protoc_insertion_point(class_scope:knowmeai.systemConfig)
  ))
_sym_db.RegisterMessage(systemConfig)
_sym_db.RegisterMessage(systemConfig.soundCnf)
_sym_db.RegisterMessage(systemConfig.skeletonCnf)
_sym_db.RegisterMessage(systemConfig.faceCnf)
_sym_db.RegisterMessage(systemConfig.communicationCnf)


# @@protoc_insertion_point(module_scope)
